stages:
    - build
    - prepare
    - push
    - release
    - upload
    - deploy

build:
    image: flamy/php-composer-node-npm
    stage: build
    only:
        - tags
    script:
        - npm prune
        - npm install -g grunt-cli
        - npm install
        - grunt package
    artifacts:
        paths:
            - dist/

prepare_push:
    stage: prepare
    only:
        - tags
    script:
        - export VERSION=$(cat VERSION)
        - echo "VERSION=$VERSION" >> vars.env
        - echo "PACKAGE_NAME=$(ls -t dist/*.zip | head -1 | xargs -n 1 basename)" >> vars.env
        - echo "PACKAGE_REGISTRY_URL=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${VERSION}" >> vars.env
    artifacts:
        reports:
            dotenv: vars.env
        paths:
            - dist/

push:
    stage: push
    image: curlimages/curl:latest
    needs:
        -   job: prepare_push
            artifacts: true
    only:
        - tags
    script:
        - ls dist
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file dist/${PACKAGE_NAME} "${PACKAGE_REGISTRY_URL}/${PACKAGE_NAME}"

deploy:
    stage: deploy
    only:
        - tags
    script:
        - grunt apertia:deploy

release:
    image: registry.gitlab.com/gitlab-org/release-cli
    stage: release
    only:
        - tags
    script:
        - >
            release-cli create --name "Release $CI_COMMIT_TAG"
            --description "Automated release $CI_COMMIT_TAG"
            --tag-name $CI_COMMIT_TAG --ref $CI_COMMIT_SHA
            --assets-link "{\"name\":\"${PACKAGE_NAME}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_NAME}\"}"

